### PR TITLE
USB printer support added

### PR DESCRIPTION
**Pull request by RealNagus**
Added an additional configuration item for printers connected through USB. If both, IP and USB settings are defined, the IP setting is preferred.
Also extended the README with available configuration options.

resolves inventree/inventree-brother-plugin#29

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@RealNagus thanks for the submission! Please address code style issues and I am happy to merge :)

**Comment by RealNagus** [comment]
Whoops! Should be fixed now. :)
Do I have to create a new PR?

**Comment by matmair** [comment]
@RealNagus this PR will be fine, the CI is now passing

**Comment by SchrodingersGat** [comment]
@RealNagus thanks for the contribution!

**Pull request merged**
